In [15]:
# Importando pacote para leitura do arquivo do excel
from pandas import read_excel
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

<img src="../files/ATP.jpg">

<h1 align="center">Análise Estatística - ATP - Big Data e Inteligência Analítica

<h2 align="center">Antonio de Padua Rodrigues Santos

<h2 align="center"> Estatística Descritiva

<h3> 1.1 Tema

<p><font size="3">Aspectos sociais que são determinantes na busca por satisfação no trabalho</font></p>

<h3> 1.2 Problema Pesquisado

<p>
    <font size="3">A desigualdade trabalhista pode ser expressa exclusivamente pela raça ou idade?
    <br>A educação poderia mudar o cenário em questão?
    </font>
</p>

<h3> 1.3 População e Amostra

<p>
    <font size="3"/>A seguir iremos analisar nossa população e coletaremos algumas amostras para análise descritiva.
</p>

In [4]:
# Carregando arquivo com os dados do projeto
populacao_original = read_excel("../files/Arquivo8.xlsx")

In [5]:
# Verificando o tamanho da 'população'
populacao_original

,Sexo,Idade,Cor ou Raça,Total de moradores (grupo familiar),Sabe ler e escrever?,Qual o curso que frequenta?,Frequentou escola?,"Tem ou teve algum trabalho remunerado ( em dinheiro, produtos, mercadorias ou benefícios)?",Quantas horas por semana poderia dedicar ao trabalho?,Trabalha atualmente?,Rendimento mensal efetivamente recebido,Qualidade de vida no ultimo trabalho
0,Homem,20,Parda,4,Sim,NaN,sim,Sim,40.0,Não,NaN,Bom
1,Homem,20,Branca,4,Sim,NaN,sim,Sim,40.0,Não,NaN,Bom
2,Homem,20,Parda,4,Sim,NaN,sim,Sim,NaN,Não,NaN,Muito Bom
3,Homem,20,Parda,5,Sim,NaN,sim,Sim,40.0,Não,NaN,Muito Bom
4,Homem,20,Parda,7,Sim,NaN,sim,Sim,NaN,Não,NaN,Muito Bom
...,...,...,...,...,...,...,...,...,...,...,...,...
51863,Mulher,49,Branca,1,Sim,Mestrado ou doutorado,NaN,NaN,NaN,Sim,20000.0,Muito Bom
51864,Homem,52,Branca,3,Sim,Superior - graduação,NaN,NaN,NaN,Sim,1500.0,Muito Bom
51865,Homem,52,Parda,5,Sim,Superior - graduação,NaN,NaN,NaN,Sim,1800.0,Muito Bom
51866,Homem,53,Branca,4,Sim,Superior - graduação,NaN,NaN,NaN,Sim,4200.0,Muito Bom
51867,Homem,54,Branca,1,Sim,Mestrado ou doutorado,NaN,NaN,NaN,Sim,5000.0,Indiferente

<p> <br>
    <font size="3"/> Nossa população é composta por 51868 registros, a seguir obteremos uma amostra de acordo com a técnica de amostragem simples.
</p>

<img src="../files/amostragem.png">

In [8]:
# Definindo a amostragem conforme o resultado do cálculo
amostraN = populacao_original.sample(39693)

In [9]:
# Amostragem Simples Obtida
amostraN

,Sexo,Idade,Cor ou Raça,Total de moradores (grupo familiar),Sabe ler e escrever?,Qual o curso que frequenta?,Frequentou escola?,"Tem ou teve algum trabalho remunerado ( em dinheiro, produtos, mercadorias ou benefícios)?",Quantas horas por semana poderia dedicar ao trabalho?,Trabalha atualmente?,Rendimento mensal efetivamente recebido,Qualidade de vida no ultimo trabalho
36999,Homem,41,Parda,3,Sim,NaN,sim,NaN,NaN,Sim,3500.0,Ruim
10118,Mulher,61,Branca,2,Sim,NaN,sim,Sim,NaN,Não,NaN,Bom
13005,Mulher,66,Branca,2,Sim,NaN,sim,Sim,NaN,Não,NaN,Muito Bom
18852,Mulher,72,Amarela,3,Sim,NaN,Não,Sim,NaN,Não,NaN,Bom
43755,Homem,51,Parda,7,Sim,NaN,sim,NaN,NaN,Sim,6500.0,Bom
...,...,...,...,...,...,...,...,...,...,...,...,...
41606,Homem,48,Parda,4,Sim,NaN,sim,NaN,NaN,Sim,2000.0,Bom
5085,Mulher,47,Branca,4,Sim,NaN,sim,Sim,NaN,Não,NaN,Muito Ruim
16081,Homem,73,Parda,2,Sim,NaN,sim,Sim,NaN,Não,NaN,Bom
42026,Mulher,48,Branca,4,Sim,NaN,sim,NaN,NaN,Sim,3000.0,Bom
42280,Homem,49,Branca,3,Sim,NaN,sim,NaN,NaN,Sim,3000.0,Bom

<p>
    <font size="3"> O número obtido através do cálculo amostral, aproximadamente foi 39693 registros, a partir de agora realizaremos um processo exploratório dos dados para responder algumas perguntas.
</p>

<h3 align="center">Quantidade de pessoas por sexo

<img src="../files/excel-sexo.jpg">

<p>
    <font size="3"> A distribuição por sexo está equilibrada, além disso é importante ressaltar que os dados que estão sendo disponibilizados correspondem à amostra solicitada.
</p>

<h3 align="center">Quantidade de pessoas por sexo e cor - Variáveis Agrupadoras

<img src="../files/excel-sexo-cor.jpg">

<img src="../files/excel-sexo-idade.jpg">